apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse-ds
    access: proxy
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: movie_analytics
      username: default
      dialTimeout: "10"
      queryTimeout: "60"
    secureJsonData:
      password: clickhouse_pass
    editable: true

  - name: PostgreSQL
    type: postgres
    uid: postgres-ds
    access: proxy
    url: postgres:5432
    database: movie_metrics
    user: metrics_user
    jsonData:
      sslmode: disable
      postgresVersion: 1500
    secureJsonData:
      password: metrics_pass
    editable: true
